### ISSUE TITLE
bpy.so do not work in OSX 10.11.15

### ISSUE THREAD

**Issue by xiazhibin** [dfelinto/blender#30]
I build successfully(get bpy.so and folder name 2.78).When `import bpy`, python3 is crashed down.
Here is the log:
`BLT_lang_init: 'locale' data path for translations not found, continuing`
`Color management: using fallback mode for management`
`bpy: couldnt find 'scripts/modules', blender probably wont start.`
`Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.`
`ImportError: No module named 'bpy_types'`
`ImportError: No module named 'bpy_types'`
`pyrna_srna_ExternalType: failed to find 'bpy_types' module`
`ImportError: No module named 'bpy_types'`
`ImportError: No module named 'bpy_types'`
`pyrna_srna_ExternalType: failed to find 'bpy_types' module`
`ImportError: No module named 'bpy_types'`
`pyrna_srna_ExternalType: failed to find 'bpy_types' module`
`F1109 11:27:29.472208 1904091136 utilities.cc:322] Check failed:!IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!`
`*** Check failure stack trace: ***`
`@        0x1051d3041`
`@        0x1051d6ff2`
`@        0x1051d3929`
`@        0x1051db2b7`
`@        0x1050ef3e0`
`@        0x10315359c`
`@        0x10355d5d6`
`@        0x100058627`
`@        0x100058a3e`
`@        0x1001164ee`
`@        0x10010f65b`
`@        0x10010e547`
`@        0x100065479`
`@        0x1000f0478`
`@        0x1000f2510`
`@        0x1000f038b`
`@        0x1000f05d6`
`@        0x1000f05d6`
`@        0x1000f05d6`
`@        0x1000f05d6`
`@        0x1000f2510`
`@        0x1000f2617`
`@        0x10004031a`
`@        0x10000d713`
`@        0x1000104b6`
`@        0x10010d0d3`
`@        0x10010d8d1`
`@        0x10355a0e7`
`@        0x10355c980`
`@        0x10316403e`
`@        0x103153654`
`@        0x10355d5d6`
`[1]    36914 abort      python3`

**Comment by xunkai55** [comment]
Hi @xiazhibin , could you please give some hints about how you fixed the problem? I'm facing the same thing now. Thank you!

**Comment by xunkai55** [comment]
Hi all, if you are facing the same problem:

I read the code and found a solution. PTAL at https://gist.github.com/xunkai55/6331fdd3446257cf5b4a98f202727245
