### ISSUE TITLE
make build error in Mac OSX

### ISSUE THREAD

**Issue by murali129** [dfelinto/blender#36]
When I tried to build the project with **make** command, it throwing the following errors which is related **git submodule**, which I am un aware of and even google could not help, great if some one can **add read.me to the project** or guide me to resolve this error, I appreciate your effort in reading my error. Thanks
![screen shot 2017-11-22 at 10 34 24 am](https://user-images.githubusercontent.com/11785843/33135632-f03f872e-cf70-11e7-8498-5a2d9e7bac05.png)

**Comment by dfelinto** [comment]
Blender is not a project really hosted on github.
You should follow this guide instead: https://wiki.blender.org/index.php/Dev:Doc/Building_Blender
