### ISSUE TITLE
Build broken for: make bpy on linux and mac os

### ISSUE THREAD

**Issue by armarwat** [dfelinto/blender#45]
Recent commits in master have broken the python module build (specifically: make bpy)

error: no matching function for call to ‘GHOST_WindowNULL::GHOST_WindowNULL(GHOST_SystemNULL*, const STR_String&, GHOST_TInt32&, GHOST_TInt32&, GHOST_TUns32&, GHOST_TUns32&, GHOST_TWindowState&, const GHOST_TEmbedderWindowID&, GHOST_TDrawingContextType&, bool, int)’

As temporary fix I rolled back the most recent commits to (../ghost/intern/* files)

More specifically (so far only on linux) I ran the following command

1) git checkout e2102e991764ae5604a9680294daaf013f344ec4

2) make bpy (to perform actual build)

**Comment by dfelinto** [comment]
You should report this upstream, this is a clone repository only (for master anyways)

**Comment by dfelinto** [comment]
(upstream is developer.blender.org)

**Comment by armarwat** [comment]
thanks will do so
