### ISSUE TITLE
New feature request - integration of JOSM into blender as a plugin or end-to-end import and export of JOSM to and from blender.

### ISSUE THREAD

**Issue by Sowa1980** [dfelinto/blender#50]
Здравствуйте, хотелось бы запросить новую функцию.

Интеграция JOSM в blender как плагин, что бы можно через него так же просто рисовать и отправлять данные, в OSM.
Очевидные плюсы:

1. простота сквозного импорт и экспорт, без сложностей из JOSM в blender и обратно.
2. идеально отточенная геометрия зданий и объектов почти с сантиметровой точностью.
3. возможность получать чертежи зданий и ландшафтов местности без особых трудностей.
4. легкость и простота в 3D Моделирование, оно станет доступным каждому, и будет не убогим костылем как есть сейчас.
5. 3D Моделирование поэтажных планов зданий станет удовольствием, с должной визуализацией.

Если это не возможно реализовать, хотелось бы попросить хотя плагин импорт и экспор, без сложностей из JOSM в blender и обратно.

Прошу Вас связаться и помочь в данной идеи с разработчиками проект https://josm.openstreetmap.de/

Очень надеюсь, что это возможно будет реализовать!

----
translated with deepL.com:

Hello, I would like to request a new feature.

Integrating JOSM into the blender as a plugin, so that you can easily draw and send data to OSM through it as well.
Obvious advantages:

1. Easy end-to-end import and export, with no hassle from JOSM to blender and back.
2. Perfectly fine-tuned geometry of buildings and objects with almost a centimeter accuracy.
3. the ability to obtain drawings of buildings and landscapes without much difficulty.
4. lightness and simplicity in 3D Modeling, it will be available to everyone, and will not be a poor crutch as it is now.
5. 3D modeling of floor plans of buildings will be a pleasure, with proper visualization.

If this is not possible, we would like to ask for an import and export plugin, without any problems from JOSM to blender and back.

I ask you to contact and help with this idea with the developers of the project https://josm.openstreetmap.de/

I very much hope that it will be possible to implement it!

**Comment by dfelinto** [comment]
Hi, this is my personal clone of the Blender repository, there is nothing I can do to handle your feature request. You are better off finding someone in https://www.blendernetwork.org/jobs/
