### ISSUE TITLE
External fonts behave weird.

### ISSUE THREAD

**Issue by ajk2196** [dfelinto/blender#55]
Hello everyone,

I recently set my Blender 2.93.4's default UI font to Merryweather. When I type anything into text editor of Blender, all the letters overlap each other by huge margin; making it almost difficult to read. I tried this with the default font and everything works fine with it. Also, there is no option to manually set the spacing between the letters in the text editor.

**Comment by dfelinto** [comment]
This is my personal mirror of the Blender repository. For the official bug tracker go to: https://developer.blender.org/
