### ISSUE TITLE
Blender lacks muscle-tear like simulation settings.

### ISSUE THREAD

**Issue by ajk2196** [dfelinto/blender#56]
Hi,

I recently had been experimenting a lot with Blender's Simulations but could not find the settings or tricks that would help me produce something like a muscle tear or a skin tear or cloth tear. I just wanted to point this out as I did see some softwares like Houdini perform this, although I don't exactly know how Houdini works.

**Comment by dfelinto** [comment]
This is my personal mirror of the Blender repository. For the official bug tracker go to: https://developer.blender.org/
